name: Go
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.x'
      - name: Install dependencies
        run: go mod tidy
      - name: 'Create env file'
        env:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          user: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          dbname: ${{ secrets.DB_NAME }}
        run: |
          touch .env
          echo host: $host >> .env
          echo port: $port >> .env
          echo user: $user >> .env
          echo password: $password >> .env
          echo dbname: $dbname >> .env
          cat .env
      - name: Build
        run: go build -v ./...
      - name: Test with the Go CLI
        run: go test
